version: "3.5"
services:
    app:  
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env 
        volumes:
            - .:/app
            - ./dist:/app/dist
        ports:
            - "${APP_PORT}:${APP_PORT}"
            - "9222:9222" 
        command: yarn start-inspect 
